[manifest]
version = "1.0.0"
priority = 999

# Common/Rare Tag tweak
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'self.ability.perishable = true'
position = 'at'
match_indent = true
payload = 'self.ability.perishable = _perishable'
times = 1

